### ISSUE TITLE
Figure out the art licensing

### ISSUE THREAD

**Issue by valdisxp1** [PolyGD/TBFights#8]

**Comment by ThibaultUrien** [comment]
I think we decided something for this. Wasn't it CC by nc sa?

**Comment by valdisxp1** [comment]
Yes, we picked CC BY NC SA. Just have to write some docs to state that the code is under Apache, but the art is under CC. Probably need a separate file for art licenses if we ever pick up stuff from other places, like opengameart.org .

Example:
```markdown
[![Creative Commons License](https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png)](http://creativecommons.org/licenses/by-nc-sa/4.0/)  
This work is licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/).
```

[![Creative Commons License](https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png)](http://creativecommons.org/licenses/by-nc-sa/4.0/)  
This work is licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/).

https://creativecommons.org/choose/results-one?license_code=by-nc-sa&amp;jurisdiction=&amp;version=4.0&amp;lang=en

**Comment by valdisxp1** [comment]
Converted html to markdown to be more easily included. Will create files for licensing soon.
